// A hacky way to do things, but a necessity.
// The content of this file will be included (prepended) in the output file generated by handlebars template.
// Hanbdlebar pre-compiled templates need variables/configuration and this file can contain them.
var Handlebars = window.Handlebars || window.HighresiO.Highbrow.Handlebars;
